### PR TITLE
Index for clouddocs

### PR DESCRIPTION
**Pull request by JosephPJordan**
new request for master for new clouddocs index

### CODE REVIEW

**Comment by Niklaus-xie** [comment]
looks like you do not have the latest from master branch? so probably you should get the latest from the master branch and then do a rebase ?

**Comment by Niklaus-xie** [comment]
HI Joe, the content modified look good to me .  but would you please use a brand new branch because when i open the Commits tab, it shows there are 37 Commits. although there should not be .   not sure why .

**Comment by JosephPJordan** [comment]
@Niklaus-xie, from which branch should I create a new one, this index branch?

**Comment by Niklaus-xie** [comment]
> @Niklaus-xie, from which branch should I create a new one, this index branch?
hello, for this pr, you wanted to merge into master branch, so you should first create  from latest master branch.
For the other pr, you wanted to merge into v1 branch, so you should create one from latest v1 branch. 
if still any questions, we can discuss via Teams . thanks

**Pull request closed without merging**
