### PR TITLE
Read the Docs - First wave ready for publication

### LINKED ISSUE #66: Read The Docs migration
1. Create new read the docs site for this repo.
 - Remove Jekyll configs, dirs, etc. (keep css)
 - Configure sphinx
 - Refactor docs which are reusing content into single continuous files
 - Convert all docs to rst and review for conversion errors.
 - Move docs to project repos as appropriate for content (where applicable)

2. Refactor the index.html.
 - Links to project rtd sites
 - About Us / Contact Us page

### PR DESCRIPTION
**Pull request by jputrino**
Fixes #66 

@swormke @mattgreene -- Would appreciate if both of you can review. 

#### What's this change do?

- Configures the f5-openstack-docs repo for read the docs (including adding the support and license files necessary to make the repo public).
- Edited the existing general OpenStack docs (Exploring OpenStack, OpenStack config guide, OpenStack deploy guide) for .rst/sphinx formatting.

#### Where should the reviewer start?
To view the docs locally:
```
git clone -b 1.0 https://github.com/jputrino/f5-openstack-docs-dep.git
cd f5-openstack-docs-dep/docs
make html
```
then view the html files in the _build directory in your browser.

#### Any background context?

As part of the migration to RTD, I created new branches (1.0, liberty) and re-created master. Develop and gh-pages haven't been touched, they're still being used to generate and host the existing GH Pages site.

### CODE REVIEW

**Comment by jputrino** [comment]
I totally forgot that making the repo public would blow up my fork. O_O Hopefully this will go through ok!

**Comment by jputrino** [comment]
http://f5-openstack-lbaasv1.readthedocs.org/en/latest/

**Comment by swormke** [comment]
Can we add sub-sections for the openstack projects on [index.rst with a short description of each and what each repo is for?

**Comment by swormke** [comment]
Can you hide or move the OpenStack CLA sidebar entry down to the bottom?

**Comment by swormke** [comment]
Docs » Exploring OpenStack and BIG-IP via the CLI

# Overview section refers to the login configured in the setup process.  What setup process is this?  Is it one that we provided or something that we assume they did?  Maybe this page needs some prerequisits?  I saw a similar page from Weave that may be a good way to look at this page. https://www.weave.works/guides/part-1-launching-weave-net-with-docker-machine/

**Comment by swormke** [comment]
## Docs » OpenStack Deployment Guide
#### Overview
* Add link to Packstack
* The warning is a little harsh, maybe soften the wording about no guarantee so something a little more friendly?

### Getting Started
* via DHCP - Is that because we use DHCP in our lab?  Maybe you should also say that that they may need to do this manually and assign a static IP?
* It looks like your code blocks (since you used shell) are thinking the command prompt of # is a comment which is why it is greyed out.  You probably just need to use the indent and no code block?
#### Install Software Repositories
* step 4 needs a space between the # and the word yum and I think the ` at the end of the line is not right either.
### Deploy OpenStack using PackStack
* Maybe a link to Heat and Neutron LBaaS?
* Answers file link is not found
* Make the '[answers_file]' text be code escaped so it looks like code text
* TIP section, where do you run that command and does that return your the name or IP address of the host?
### Configure OpenStack
* What URL provided for Horizon?

**Comment by swormke** [comment]
## Docs » OpenStack Configuration Guide
### Overview
* maybe link to the instructions on how to setup the all in one.  You never know how the user ended up on this page.

**Comment by jputrino** [comment]
I'm closing this one out and opening a new one, since I blew things up by making the repo public mid-pull request.

**Pull request closed without merging**
